### ISSUE TITLE
Controller Spawner couldn't find the expected controller_manager ROS interface

### ISSUE THREAD

**Issue by mos127** [wunderkammer-laboratory/steered_wheel_base_controller#2]
Hi there,

I'm trying to launch the controller to test it on my robot in the Gazebo but this error appears. I use ROS indigo version. My own controller works fine without any error but I am interested to test this controller on my robot.
Any idea or solution would be appreciated.

Thanks!

**Comment by wunderkammer-laboratory** [comment]
Make certain that you have installed all the build_depend and run_depend packages listed in steered_wheel_base_controller's package.xml. If the error still occurs, please post the terminal output from roslaunch, including the error message. Also, post the element in your launch file where you launch the controller spawner.

**Comment by mos127** [comment]
I checked all the dependencies and the are all installed:

mos@ubuntu:~/catkin_workspace$ rosdep check steered_wheel_base_controller
All system dependencies have been satisified

This is the terminal output : 

... logging to /home/mos/.ros/log/f6395eb4-5693-11e5-8fb5-000c29367276/roslaunch-ubuntu-4403.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:47336/

SUMMARY
========

PARAMETERS
 * /base_ctrlr/linear_acceleration_limit: 0.5
 * /base_ctrlr/linear_deceleration_limit: 0.5
 * /base_ctrlr/linear_speed_limit: 2.0
 * /base_ctrlr/type: steered_wheel_bas...
 * /base_ctrlr/wheels: [{'diameter': 0.0...
 * /base_ctrlr/yaw_acceleration_limit: 1.5
 * /base_ctrlr/yaw_deceleration_limit: 5.0
 * /base_ctrlr/yaw_speed_limit: 2.0
 * /crossrob_joint_publisher/publish_rate: 50
 * /crossrob_joint_publisher/type: joint_state_contr...
 * /robot_description: <?xml version="1....
 * /rosdistro: indigo
 * /rosversion: 1.11.13
 * /use_sim_time: True

NODES
  /
    base_controller_spawner (controller_manager/spawner)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    urdf_spawner (gazebo_ros/spawn_model)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[gazebo-1]: started with pid [4424]
process[gazebo_gui-2]: started with pid [4431]
process[urdf_spawner-3]: started with pid [4438]
process[base_controller_spawner-4]: started with pid [4441]
Gazebo multi-robot simulator, version 2.2.5
Copyright (C) 2012-2014 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

Gazebo multi-robot simulator, version 2.2.5
Copyright (C) 2012-2014 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

Msg Waiting for master.[ INFO] [1441764740.944444954]: Finished loading Gazebo ROS API Plugin.
[1;[ INFO] [1441764740.945992137]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
32mMsg Waiting for master
Msg Connected to gazebo master @ http://127.0.0.1:11345
Msg Publicized address: 192.168.244.129

Msg Connected to gazebo master @ http://127.0.0.1:11345
Msg Publicized address: 192.168.244.129
Warning [gazebo.cc:215] Waited 1seconds for namespaces.
[ INFO] [1441764743.240818655, 0.021000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1441764743.342428053, 0.092000000]: Physics dynamic reconfigure ready.
spawn_model script started
[INFO] [WallTime: 1441764743.710381] [0.000000] Loading model xml from ros parameter
[INFO] [WallTime: 1441764743.714057] [0.000000] Waiting for service /gazebo/spawn_urdf_model
[INFO] [WallTime: 1441764743.715798] [0.000000] Calling service /gazebo/spawn_urdf_model
Error [InsertModelWidget.cc:233] Missing model.config for model "/home/mos/.gazebo/models/sancaground"
Error [InsertModelWidget.cc:233] Missing model.config for model "/home/mos/.gazebo/models/sancasun"
[INFO] [WallTime: 1441764745.229894] [1.840000] Spawn status: SpawnModel: Successfully spawned model
[urdf_spawner-3] process has finished cleanly
log file: /home/mos/.ros/log/f6395eb4-5693-11e5-8fb5-000c29367276/urdf_spawner-3*.log
[ INFO] [1441764755.164424879, 1.840000000]: Loading gazebo_ros_control plugin
[ INFO] [1441764755.164878712, 1.840000000]: Starting gazebo_ros_control plugin in namespace: /crossrob
[ INFO] [1441764755.165845540, 1.840000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [/robot_description] on the ROS param server.
[ INFO] [1441764755.638403082, 1.840000000]: Loaded gazebo_ros_control.
Dbg plugin model name: crossrob
[WARN] [WallTime: 1441764770.281973] [7.754000] Controller Spawner couldn't find the expected controller_manager ROS interface.
[base_controller_spawner-4] process has finished cleanly
log file: /home/mos/.ros/log/f6395eb4-5693-11e5-8fb5-000c29367276/base_controller_spawner-4*.log

and this is the launch file : 

<?xml version="1.0"?>
<launch>

  
  <rosparam file="$(find crossrob_control)/config/base_ctrlr_params.yaml" command="load"/>

  
  <node name="base_controller_spawner" pkg="controller_manager" type="spawner" args="crossrob_joint_publisher base_ctrlr"/>

</launch>


Also the yaml file:

crossrob_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50


base_ctrlr:
  type: "steered_wheel_base_controller/SteeredWheelBaseController"

  linear_speed_limit: 2.0
  linear_acceleration_limit: 0.5
  linear_deceleration_limit: 0.5

  yaw_speed_limit: 2.0
  yaw_acceleration_limit: 1.5
  yaw_deceleration_limit: 5.0

  wheels:
    - steering_joint: servo1
      axle_joint: motor1
      diameter: 0.06
    - steering_joint: servo2
      axle_joint: motor2
      diameter: 0.06
    - steering_joint: servo3
      axle_joint: motor3
      diameter: 0.06
    - steering_joint: servo4
      axle_joint: motor4
      diameter: 0.06

**Comment by wunderkammer-laboratory** [comment]
<?xml version="1.0"?>

    

    

Where is the "node" element? It should look something like this:

    <node name="controller_spawner" pkg="controller_manager" type="spawner"
          args="$(find crossrob_bringup)/config/ctrlr_params.yaml"/>

**Comment by mos127** [comment]
Sorry that was my mistake I don't know why it didn't the main lines, here's the launch file again:

<?xml version="1.0"?>
<launch>

  
  <rosparam file="$(find crossrob_control)/config/base_ctrlr_params.yaml" command="load"/>

  
  <node name="base_controller_spawner" pkg="controller_manager" type="spawner" args="crossrob_joint_publisher base_ctrlr"/>

</launch>

**Comment by mos127** [comment]
Sorry that was my mistake, I don't know why it didn't copy the main lines:

  <?xml version="1.0"?>
  <launch>

    
    <rosparam file="$(find crossrob_control)/config/base_ctrlr_params.yaml" command="load"/>

    
    <node name="base_controller_spawner" pkg="controller_manager" type="spawner"     args="crossrob_joint_publisher base_ctrlr"/>

  </launch>

**Comment by mos127** [comment]
An update! I changed the launch file and yaml file to this:
```
<launch>

  <!-- Load joint controller configurations from YAML file to parameter server -->
  <rosparam file="$(find crossrob_control)/config/base_ctrlr_params.yaml" command="load"/>

  <node name="controller_spawner"
    pkg="controller_manager"
    type="spawner" respawn="false"
    output="screen" ns="/crossrob"
    args="crossrob_joint_publisher
           base_ctrlr"

  />
</launch>
```
And the yaml file:
```
crossrob:  
  crossrob_joint_publisher:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50


  base_ctrlr:
    type: "steered_wheel_base_controller/SteeredWheelBaseController"

    linear_speed_limit: 2.0
    linear_acceleration_limit: 0.5
    linear_deceleration_limit: 0.5

    yaw_speed_limit: 2.0
    yaw_acceleration_limit: 1.5
    yaw_deceleration_limit: 5.0

    wheels:
      - steering_joint: servo1
        axle_joint: motor1
        diameter: 0.06
      - steering_joint: servo2
        axle_joint: motor2
        diameter: 0.06
      - steering_joint: servo3
        axle_joint: motor3
        diameter: 0.06
      - steering_joint: servo4
        axle_joint: motor4
        diameter: 0.06
```
In this case, it seems the last error doesn't occur! but, the new error appears.
This is the terminal output:
```
... logging to /home/mos/.ros/log/4f1600a0-56a3-11e5-85fc-000c29367276/roslaunch-ubuntu-8970.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:51008/

SUMMARY
========

PARAMETERS
 * /crossrob/base_ctrlr/linear_acceleration_limit: 0.5
 * /crossrob/base_ctrlr/linear_deceleration_limit: 0.5
 * /crossrob/base_ctrlr/linear_speed_limit: 2.0
 * /crossrob/base_ctrlr/type: steered_wheel_bas...
 * /crossrob/base_ctrlr/wheels: [{'diameter': 0.0...
 * /crossrob/base_ctrlr/yaw_acceleration_limit: 1.5
 * /crossrob/base_ctrlr/yaw_deceleration_limit: 5.0
 * /crossrob/base_ctrlr/yaw_speed_limit: 2.0
 * /crossrob/crossrob_joint_publisher/publish_rate: 50
 * /crossrob/crossrob_joint_publisher/type: joint_state_contr...
 * /robot_description: <?xml version="1....
 * /rosdistro: indigo
 * /rosversion: 1.11.13
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    urdf_spawner (gazebo_ros/spawn_model)
  /crossrob/
    controller_spawner (controller_manager/spawner)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[gazebo-1]: started with pid [8991]
process[gazebo_gui-2]: started with pid [8999]
Gazebo multi-robot simulator, version 2.2.5
Copyright (C) 2012-2014 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

Gazebo multi-robot simulator, version 2.2.5
Copyright (C) 2012-2014 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

process[urdf_spawner-3]: started with pid [9007]
[ INFO] [1441769520.846284005]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1441769520.852563598]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
Msg Waiting for master
Msg Connected to gazebo master @ http://127.0.0.1:11345
Msg Publicized address: 192.168.244.129
Msg Waiting for master
Msg Connected to gazebo master @ http://127.0.0.1:11345
Msg Publicized address: 192.168.244.129
process[crossrob/controller_spawner-4]: started with pid [9037]
[ INFO] [1441769521.624299317, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1441769521.729033213, 0.087000000]: Physics dynamic reconfigure ready.
spawn_model script started
[INFO] [WallTime: 1441769522.145806] [0.000000] Loading model xml from ros parameter
[INFO] [WallTime: 1441769522.162796] [0.000000] Waiting for service /gazebo/spawn_urdf_model
[INFO] [WallTime: 1441769522.188831] [0.000000] Calling service /gazebo/spawn_urdf_model
Error [InsertModelWidget.cc:233] Missing model.config for model "/home/mos/.gazebo/models/sancaground"
Error [InsertModelWidget.cc:233] Missing model.config for model "/home/mos/.gazebo/models/sancasun"
[INFO] [WallTime: 1441769522.272559] [0.000000] Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [WallTime: 1441769524.589074] [2.822000] Spawn status: SpawnModel: Successfully spawned model
[urdf_spawner-3] process has finished cleanly
log file: /home/mos/.ros/log/4f1600a0-56a3-11e5-85fc-000c29367276/urdf_spawner-3*.log
[ INFO] [1441769533.030950931, 2.822000000]: Loading gazebo_ros_control plugin
[ INFO] [1441769533.035178324, 2.822000000]: Starting gazebo_ros_control plugin in namespace: /crossrob
[ INFO] [1441769533.036195986, 2.822000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [/robot_description] on the ROS param server.
[ INFO] [1441769533.271084986, 2.822000000]: Loaded gazebo_ros_control.
Dbg plugin model name: crossrob
[INFO] [WallTime: 1441769533.441602] [2.888000] Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [WallTime: 1441769533.442765] [2.888000] Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [WallTime: 1441769533.443914] [2.888000] Loading controller: crossrob_joint_publisher
[INFO] [WallTime: 1441769533.586527] [2.912000] Loading controller: base_ctrlr
[ WARN] [1441769533.744089215, 2.937000000]: The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
gzserver: /usr/include/boost/smart_ptr/shared_ptr.hpp:653: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = urdf::JointLimits; typename boost::detail::sp_member_access<T>::type = urdf::JointLimits*]: Assertion `px != 0' failed.
Traceback (most recent call last):
  File "/home/mos/catkin_ws/src/ros_control/controller_manager/scripts/spawner", line 212, in <module>
    if __name__ == '__main__': main()
  File "/home/mos/catkin_ws/src/ros_control/controller_manager/scripts/spawner", line 190, in main
    resp = load_controller(name)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details
[INFO] [WallTime: 1441769533.928628] [2.938000] Shutting down spawner. Stopping and unloading controllers...
Aborted (core dumped)
[gazebo-1] process has died [pid 8991, exit code 134, cmd /home/mos/catkin_ws/src/gazebo_ros_pkgs/gazebo_ros/scripts/gzserver -e ode /home/mos/catkin_ws/src/crossrob/crossrob_gazebo/worlds/crossrob.world __name:=gazebo __log:=/home/mos/.ros/log/4f1600a0-56a3-11e5-85fc-000c29367276/gazebo-1.log].
log file: /home/mos/.ros/log/4f1600a0-56a3-11e5-85fc-000c29367276/gazebo-1*.log
^[[1;2B[INFO] [WallTime: 1441769573.083146] [2.938000] Stopping all controllers...
[WARN] [WallTime: 1441769573.084506] [2.938000] Controller Spawner couldn't reach controller_manager to take down controllers. Waited for 30 second(s).
[crossrob/controller_spawner-4] process has died [pid 9037, exit code 1, cmd /home/mos/catkin_ws/src/ros_control/controller_manager/scripts/spawner crossrob_joint_publisher base_ctrlr __name:=controller_spawner __log:=/home/mos/.ros/log/4f1600a0-56a3-11e5-85fc-000c29367276/crossrob-controller_spawner-4.log].
log file: /home/mos/.ros/log/4f1600a0-56a3-11e5-85fc-000c29367276/crossrob-controller_spawner-4*.log
```
Is it something with my URDF file and base_link?

**Comment by wunderkammer-laboratory** [comment]
It looks as if this is the problem:

    The root link base_link has an inertia specified in the URDF, but KDL does not support a root link
    with an inertia.  As a workaround, you can add an extra dummy link to your URDF.

It appears that you have an "inertial" element in your base_link. The base_link in em_3905.urdf.xacro in the ackermann_vehicle_description package looks like this:

    <material name="chassis_mat">
      <color rgba="0.5 0.5 0.5 1"/>
    </material>

    
    <link name="base_link">
      <visual>
        <geometry>
          <box size="0.01 0.01 0.01"/>
        </geometry>
        <material name="chassis_mat"/>
      </visual>
    </link>
    <gazebo reference="base_link">
      <material>Gazebo/Grey</material>
    </gazebo>

base_link is attached to the chassis like this:

    <joint name="base_link_to_chasis" type="fixed">
      <parent link="base_link"/>
      <child link="chassis"/>
    </joint>

**Comment by mos127** [comment]
Thanks
1 I fixed this problem and the error about base_link and inertia does not appear anymore but the rest of errors are still there. 
```
... logging to /home/mos/.ros/log/86f9a45a-5729-11e5-b5ff-000c29367276/roslaunch-ubuntu-29081.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:59245/

SUMMARY
========

PARAMETERS
 * /crossrob/base_ctrlr/linear_acceleration_limit: 0.5
 * /crossrob/base_ctrlr/linear_deceleration_limit: 0.5
 * /crossrob/base_ctrlr/linear_speed_limit: 2.0
 * /crossrob/base_ctrlr/type: steered_wheel_bas...
 * /crossrob/base_ctrlr/wheels: [{'diameter': 0.0...
 * /crossrob/base_ctrlr/yaw_acceleration_limit: 1.5
 * /crossrob/base_ctrlr/yaw_deceleration_limit: 5.0
 * /crossrob/base_ctrlr/yaw_speed_limit: 2.0
 * /crossrob/crossrob_joint_publisher/publish_rate: 50
 * /crossrob/crossrob_joint_publisher/type: joint_state_contr...
 * /robot_description: <?xml version="1....
 * /rosdistro: indigo
 * /rosversion: 1.11.13
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    urdf_spawner (gazebo_ros/spawn_model)
  /crossrob/
    controller_spawner (controller_manager/spawner)

auto-starting new master
process[master]: started with pid [29096]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 86f9a45a-5729-11e5-b5ff-000c29367276
process[rosout-1]: started with pid [29109]
started core service [/rosout]
process[gazebo-2]: started with pid [29112]
process[gazebo_gui-3]: started with pid [29141]
process[urdf_spawner-4]: started with pid [29147]
process[crossrob/controller_spawner-5]: started with pid [29150]
Gazebo multi-robot simulator, version 2.2.5
Copyright (C) 2012-2014 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

Gazebo multi-robot simulator, version 2.2.5
Copyright (C) 2012-2014 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

Msg Waiting for master.[ INFO] [1441827160.198824116]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1441827160.200605851]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
Msg Waiting for master
Msg Connected to gazebo master @ http://127.0.0.1:11345
Msg Publicized address: 192.168.244.129
spawn_model script started
[INFO] [WallTime: 1441827160.347646] [0.000000] Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [WallTime: 1441827160.515783] [0.000000] Loading model xml from ros parameter
[INFO] [WallTime: 1441827160.518587] [0.000000] Waiting for service /gazebo/spawn_urdf_model
[ INFO] [1441827160.678142919, 0.021000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1441827160.734704073, 0.058000000]: Physics dynamic reconfigure ready.
[INFO] [WallTime: 1441827160.825068] [0.133000] Calling service /gazebo/spawn_urdf_model

Msg Connected to gazebo master @ http://127.0.0.1:11345
Msg Publicized address: 192.168.244.129
Error [InsertModelWidget.cc:233] Missing model.config for model "/home/mos/.gazebo/models/sancaground"
Error [InsertModelWidget.cc:233] Missing model.config for model "/home/mos/.gazebo/models/sancasun"
[INFO] [WallTime: 1441827162.829776] [1.877000] Spawn status: SpawnModel: Successfully spawned model
[urdf_spawner-4] process has finished cleanly
log file: /home/mos/.ros/log/86f9a45a-5729-11e5-b5ff-000c29367276/urdf_spawner-4*.log
[ INFO] [1441827172.238045627, 1.877000000]: Loading gazebo_ros_control plugin
[ INFO] [1441827172.238455375, 1.877000000]: Starting gazebo_ros_control plugin in namespace: /crossrob
[ INFO] [1441827172.241002512, 1.877000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [/robot_description] on the ROS param server.
[ INFO] [1441827172.610114869, 1.877000000]: Loaded gazebo_ros_control.
Dbg plugin model name: crossrob
[INFO] [WallTime: 1441827172.717913] [1.915000] Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [WallTime: 1441827172.719080] [1.915000] Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [WallTime: 1441827172.720936] [1.915000] Loading controller: crossrob_joint_publisher
[INFO] [WallTime: 1441827172.871343] [1.939000] Loading controller: base_ctrlr
gzserver: /usr/include/boost/smart_ptr/shared_ptr.hpp:653: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = urdf::JointLimits; typename boost::detail::sp_member_access<T>::type = urdf::JointLimits*]: Assertion `px != 0' failed.
Traceback (most recent call last):
  File "/home/mos/catkin_ws/src/ros_control/controller_manager/scripts/spawner", line 212, in <module>
    if __name__ == '__main__': main()
  File "/home/mos/catkin_ws/src/ros_control/controller_manager/scripts/spawner", line 190, in main
    resp = load_controller(name)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details
[INFO] [WallTime: 1441827173.538652] [1.975000] Shutting down spawner. Stopping and unloading controllers...
Aborted (core dumped)
[gazebo-2] process has died [pid 29112, exit code 134, cmd /home/mos/catkin_ws/src/gazebo_ros_pkgs/gazebo_ros/scripts/gzserver -e ode /home/mos/catkin_ws/src/crossrob/crossrob_gazebo/worlds/crossrob.world __name:=gazebo __log:=/home/mos/.ros/log/86f9a45a-5729-11e5-b5ff-000c29367276/gazebo-2.log].
log file: /home/mos/.ros/log/86f9a45a-5729-11e5-b5ff-000c29367276/gazebo-2*.log
[WARN] [WallTime: 1441827204.540657] [1.975000] Controller Spawner couldn't reach controller_manager to take down controllers. Waited for 30 second(s).
[crossrob/controller_spawner-5] process has died [pid 29150, exit code 1, cmd /home/mos/catkin_ws/src/ros_control/controller_manager/scripts/spawner crossrob_joint_publisher base_ctrlr __name:=controller_spawner __log:=/home/mos/.ros/log/86f9a45a-5729-11e5-b5ff-000c29367276/crossrob-controller_spawner-5.log].
log file: /home/mos/.ros/log/86f9a45a-5729-11e5-b5ff-000c29367276/crossrob-controller_spawner-5*.log
```
If I just load the joint_state_publisher everything is OK without error, but by including the controller the above error still appears.

**Comment by wunderkammer-laboratory** [comment]
[INFO] [WallTime: 1441827172.871343] [1.939000] Loading controller: base_ctrlr
    gzserver: /usr/include/boost/smart_ptr/shared_ptr.hpp:653: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = urdf::JointLimits; typename boost::detail::sp_member_access<T>::type = urdf::JointLimits*]: Assertion `px != 0' failed.

It appears that there is a null pointer to a urdf::JointLimits object. Please post the URDF definitions of one of your steering joints and the corresponding drive axle joint. They should look similar to this:

    <joint name="front_steering_joint" type="revolute">
      <parent link="chassis"/>
      <child link="front_steering_axle"/>
      <origin xyz="1 0 0.25"/>
      <axis xyz="0 0 1"/>
      <limit lower="${lower_steer_limit}" upper="${upper_steer_limit}"
             effort="${motor_eff_limit}" velocity="${steer_vel_limit}"/>
    </joint>
    <transmission name="front_steering_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="front_steering_joint">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="front_steering_act">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <joint name="front_axle_joint" type="continuous">
      <parent link="front_wheel_module"/>
      <child link="front_wheel_hub"/>
      <origin xyz="0 0 0.1"/>
      <axis xyz="0 0 1"/>
      <limit effort="${axle_eff_limit}" velocity="${axle_vel_limit}"/>
    </joint>
    <transmission name="front_axle_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="front_axle_joint">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="front_axle_act">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

I suspect that the steering and drive joints in your robot lack &lt;limit&gt; elements.

**Comment by mos127** [comment]
Hi Thank you so much for that!

I fixed the URDF file to have joint limits and also I added pid gains now everything seems working without any error but I need to calibrate the system and play around with order of the wheels.

**Comment by wunderkammer-laboratory** [comment]
Are your robot's steering joints revolute, or continuous? I removed the limits from one of my robot's steering joints (which is revolute), and I get a failure during URDF parsing, instead of the null pointer problem that you experienced.

**Comment by mos127** [comment]
I have them defined as continues joint:
```
<joint name="servo4" type="continuous">

    <origin xyz="0.025 0.038892 0" rpy="0 -0.81158 3.1416" />

    <parent link="link4" />

    <child link="link44" />

    <axis xyz="0 -1 0" />

    <limit effort="0.5649" lower="-1.57079633" upper="1.57079633" velocity="4.553"/>

  </joint>
```
An interesting question: what are your steering joint limits for the independent steering wheels robot?
Can it turn 360 degrees?

**Comment by wunderkammer-laboratory** [comment]
An interesting question: what are your steering joint limits for the independent steering wheels robot?
    Can it turn 360 degrees?

Since I am using revolute steering joints (see the front_steering_joint definition above), the range is controlled by the lower and upper limits.

    <xacro:property name="lower_steer_limit" value="-2.3562"/>
    <xacro:property name="upper_steer_limit" value="2.3562"/>

lower_steer_limit is 1.5 * -(pi / 2) and upper_steer_limit is 1.5 * (pi / 2). The range is constrained to [-2.3562, 2.3562] because the drive motor and encoder cables are wrapped around the steering axle.

Concerning the servo4 joint above, no lower and upper limits should be specified for a continuous joint (see http://wiki.ros.org/urdf/XML/joint). If you want such limits, you should use a revolute joint.

**Comment by mos127** [comment]
Thanks for the recommendation, I fixed that to a revolute joint.
I also had to use VelocityJointInterface and PositionJointInterface for motor and servo joints. EffortJointVelocity didn't work well with your controller.
This controller subscribes to cmd_vel topic which takes linear.x , linear.y and angular.z.
I can see changing the linear.x and linear.y do the job very well, but angular.z seems not working well (or again maybe it's a problem with my urdf definitions).
How it should behave for your controller? Whould it possible to have zero turn(spot turn)?

**Comment by wunderkammer-laboratory** [comment]
EffortJointVelocity didn't work well with your controller.

Do you mean EffortJointInterface? Effort-controlled joints require PID controller values to be specified in pid_gains/<joint name> parameters. If you are not using the base controller to perform PID control, e.g. when it is controlling a Gazebo robot, but not a real robot, PositionJointInterface and VelocityJointInterface are much easier to use. Make certain that the joints controlled by the base controller have reasonable effort limits.

    but angular.z seems not working well (or again maybe it's a problem with my urdf definitions).
    How it should behave for your controller? Whould it possible to have zero turn(spot turn)?

Yes. If linear.x and linear.y are zero, and angular.z is nonzero, the robot should rotate around the z axis of the frame specified by the base_frame parameter. Are you publishing to cmd_vel at least twice per second? If not, set the cmd_vel_timeout parameter to 0.0.

**Comment by mos127** [comment]
Hi, I fixed the joint interfaces from effort type to position and velocity types and now Vx and Vy works great on the robot. 
There is one problem with the giving just angular.z command : in this case the wheels should turn 45 degrees (two of them 45 and two others -45) to do a spot turn. The problem is they turn 45 in the other way (for example if my first wheel should be 45, it's -45 and the same problem for the rest of the wheels). I even re-ordered the wheels based on the yaml example you provided on wiki page. This didn't help. 
Any idea of how I can solve this problem? How the order of the wheels are important to be defined properly in urdf file for your controller?

Thanks!

**Comment by wunderkammer-laboratory** [comment]
The problem is they turn 45 in the other way (for example if my first wheel should be 45, it's -45 and 
    the same problem for the rest of the wheels). I even re-ordered the wheels based on the yaml 
    example you provided on wiki page. This didn't help.
    Any idea of how I can solve this problem? How the order of the wheels are important to be defined 
    properly in urdf file for your controller?

The order of the wheels does not matter. It sounds as if you have your steering joints set up so that a positive rotation causes them to turn right. They need to turn left. Specifically, the robot's base frame should have its x axis point forward, y axis point left, and z axis point up. The frames connected to the steering joints should work the same way. When the position of a steering joint is zero, the joint's child link should have its x axis point forward, y axis point left, and z axis point up. When the robot is viewed from above, a positive rotation of a steering joint will cause the joint to rotate counterclockwise. Load your robot into RViz to make sure this is happening. If it isn't, fix the problem by modifying the "axis" elements of the steering joints so that the joints rotate the correct direction.

**Comment by wunderkammer-laboratory** [comment]
Is the base controller working for you now? I'd like to know whether I can close this issue.

**Comment by mos127** [comment]
Hi,

Sorry for keeping this issue open. Yes it works perfectly fine!
